/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eighteengray_imageprocesslibrary_ImageProcessJni */

#ifndef _Included_com_eighteengray_imageprocesslibrary_ImageProcessJni
#define _Included_com_eighteengray_imageprocesslibrary_ImageProcessJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    toGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_toGray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    toWhiteBlack
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_toWhiteBlack
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    toCameo
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_toCameo
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    zoom
 * Signature: ([IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_zoom
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    dilation
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_dilation
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    erosion
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_erosion
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    thinning
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_thinning
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    blurPixels
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_blurPixels
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_faceDetection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    initLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_initLoad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_eighteengray_imageprocesslibrary_ImageProcessJni
 * Method:    beautySkinFilter
 * Signature: (JJFZ)V
 */
JNIEXPORT void JNICALL Java_com_eighteengray_imageprocesslibrary_ImageProcessJni_beautySkinFilter
  (JNIEnv *, jclass, jlong, jlong, jfloat, jboolean);

#ifdef __cplusplus
}
#endif
#endif
